name: Update Crime Data

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - run: pip install -r requirements.txt
    - env:
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
      run: python main.py
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add crime_data.db
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update crime data" && git push)
